USE [blackbox]
GO
/****** Object:  Table [dbo].[BB_APPLICATION_BASE]    Script Date: 30-12-2015 14:38:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_APPLICATION_BASE](
	[BB_APPLICATION_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [numeric](19, 0) NULL,
	[CREATED_ON] [datetime] NULL,
	[MODIFIED_BY] [numeric](19, 0) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[APPLICATION_NUMBER_RAW] [varchar](255) NOT NULL,
	[CHILD_APPLICATION_TYPE] [varchar](255) NULL,
	[CONFIRMATION_NUMBER] [varchar](255) NULL,
	[FILING_DATE] [datetime] NULL,
	[APPLICATION_NUMBER] [varchar](255) NULL,
	[DESCRIPTION] [varchar](255) NULL,
	[FAMILY_ID] [varchar](255) NULL,
	[ENTITY] [varchar](255) NULL,
	[EXPORT_CONTROL] [bit] NULL,
	[IDS_RELEVANT_STATUS] [varchar](255) NULL,
	[PROSECUTION_STATUS] [varchar](255) NULL,
	[ART_UNIT] [varchar](255) NULL,
	[EXAMINER] [varchar](255) NULL,
	[FIRST_NAME_INVENTOR] [varchar](255) NULL,
	[ISSUED_ON] [datetime] NULL,
	[PATENT_NUMBER] [varchar](255) NULL,
	[PATENT_NUMBER_RAW] [varchar](255) NULL,
	[TITLE] [varchar](255) NULL,
	[PUBLICATION_NUMBER] [varchar](255) NULL,
	[PUBLICATION_NUMBER_RAW] [varchar](255) NULL,
	[PUBLISHED_ON] [datetime] NULL,
	[SOURCE] [varchar](255) NULL,
	[SUB_SOURCE] [varchar](255) NULL,
	[BB_NEW_RECORD_STATUS] [varchar](255) NULL,
	[RECORD_STATUS] [varchar](255) NULL,
	[SCENARIO] [varchar](255) NULL,
	[BB_COMMENT] [varchar](255) NULL,
	[VERSION] [int] NULL,
	[BB_ASSIGNEE] [numeric](19, 0) NOT NULL,
	[BB_ATTORNEY_DOCKET] [numeric](19, 0) NOT NULL,
	[BB_CUSTOMER] [numeric](19, 0) NOT NULL,
	[BB_JURISDICTION] [numeric](19, 0) NOT NULL,
	[BB_ORGANIZATION] [numeric](19, 0) NOT NULL,
	[BB_TECHNOLOGY_GROUP] [numeric](19, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_APPLICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_tkb6lm8cvmfhemd4umakx7a3h] UNIQUE NONCLUSTERED 
(
	[BB_JURISDICTION] ASC,
	[APPLICATION_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BB_APPLICATION_STAGE]    Script Date: 30-12-2015 14:38:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_APPLICATION_STAGE](
	[BB_APPLICATION_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [numeric](19, 0) NULL,
	[CREATED_ON] [datetime] NULL,
	[MODIFIED_BY] [numeric](19, 0) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[APPLICATION_NUMBER_RAW] [varchar](255) NOT NULL,
	[CHILD_APPLICATION_TYPE] [varchar](255) NULL,
	[CONFIRMATION_NUMBER] [varchar](255) NULL,
	[FILING_DATE] [datetime] NULL,
	[APPLICATION_NUMBER] [varchar](255) NULL,
	[DESCRIPTION] [varchar](255) NULL,
	[FAMILY_ID] [varchar](255) NULL,
	[ENTITY] [varchar](255) NULL,
	[EXPORT_CONTROL] [bit] NULL,
	[IDS_RELEVANT_STATUS] [varchar](255) NULL,
	[PROSECUTION_STATUS] [varchar](255) NULL,
	[ART_UNIT] [varchar](255) NULL,
	[EXAMINER] [varchar](255) NULL,
	[FIRST_NAME_INVENTOR] [varchar](255) NULL,
	[ISSUED_ON] [datetime] NULL,
	[PATENT_NUMBER] [varchar](255) NULL,
	[PATENT_NUMBER_RAW] [varchar](255) NULL,
	[TITLE] [varchar](255) NULL,
	[PUBLICATION_NUMBER] [varchar](255) NULL,
	[PUBLICATION_NUMBER_RAW] [varchar](255) NULL,
	[PUBLISHED_ON] [datetime] NULL,
	[SOURCE] [varchar](255) NULL,
	[SUB_SOURCE] [varchar](255) NULL,
	[BB_ASSIGNEE] [varchar](255) NULL,
	[BB_ATTORNEY_DOCKET] [varchar](255) NULL,
	[BB_CUSTOMER] [varchar](255) NULL,
	[BB_JURISDICTION] [varchar](255) NULL,
	[BB_ORGANIZATION] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_APPLICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_e31k26t0gm1j4ruqmi4l4vm5u] UNIQUE NONCLUSTERED 
(
	[BB_JURISDICTION] ASC,
	[APPLICATION_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BB_VALID_FORMAT]    Script Date: 30-12-2015 14:38:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_VALID_FORMAT](
	[BB_VALID_FORMAT_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[CONVERTER_STRATEGY] [varchar](255) NULL,
	[REGEX_PATTERN] [varchar](255) NULL,
	[REQ_FORMAT] [varchar](255) NULL,
	[VALID_FORMAT] [varchar](255) NULL,
	[BB_VALIDATION_MATRIX_ID] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_VALID_FORMAT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BB_VALIDATION_MATRIX]    Script Date: 30-12-2015 14:38:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_VALIDATION_MATRIX](
	[BB_VALIDATION_MATRIX_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[APPLICATION_TYPE] [varchar](255) NULL,
	[CHECK_NUM_EQUALITY] [varchar](255) NULL,
	[END_FILING_DATE] [datetime] NULL,
	[END_GRANT_DATE] [datetime] NULL,
	[JURISDICTION] [varchar](255) NULL,
	[NUMBER_TYPE] [varchar](255) NULL,
	[START_FILING_DATE] [datetime] NULL,
	[START_GRANT_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_VALIDATION_MATRIX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE]  WITH CHECK ADD  CONSTRAINT [FK_8dy64l22omlmkwstf2dw318j4] FOREIGN KEY([BB_CUSTOMER])
REFERENCES [dbo].[BB_MSTR_CUSTOMER] ([BB_CUSTOMER_ID])
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE] CHECK CONSTRAINT [FK_8dy64l22omlmkwstf2dw318j4]
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE]  WITH CHECK ADD  CONSTRAINT [FK_axcjjwrfv7kityvhegeit2spb] FOREIGN KEY([BB_JURISDICTION])
REFERENCES [dbo].[BB_MSTR_JURISDICTION] ([BB_JURISDICTION_ID])
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE] CHECK CONSTRAINT [FK_axcjjwrfv7kityvhegeit2spb]
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE]  WITH CHECK ADD  CONSTRAINT [FK_c5tel7bqr8dyqvwqoqkjaml4s] FOREIGN KEY([BB_TECHNOLOGY_GROUP])
REFERENCES [dbo].[BB_MSTR_TECHNOLOGY_GROUP] ([BB_TECHNOLOGY_GROUP_ID])
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE] CHECK CONSTRAINT [FK_c5tel7bqr8dyqvwqoqkjaml4s]
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE]  WITH CHECK ADD  CONSTRAINT [FK_fshacam0ln11ifhm0j0g1qfix] FOREIGN KEY([BB_ATTORNEY_DOCKET])
REFERENCES [dbo].[BB_ATTRONEY_DOCKET_NUMBER] ([BB_ATTORNEY_DOCKET_NUMBER_ID])
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE] CHECK CONSTRAINT [FK_fshacam0ln11ifhm0j0g1qfix]
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE]  WITH CHECK ADD  CONSTRAINT [FK_hp6ukcm5blo6vcmu1a3nbjcka] FOREIGN KEY([BB_ORGANIZATION])
REFERENCES [dbo].[BB_ORGANIZATION] ([BB_ORGANIZATION_ID])
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE] CHECK CONSTRAINT [FK_hp6ukcm5blo6vcmu1a3nbjcka]
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE]  WITH CHECK ADD  CONSTRAINT [FK_rvcmgrd38bs1va6exn18ea2j6] FOREIGN KEY([BB_ASSIGNEE])
REFERENCES [dbo].[BB_ASSIGNEE] ([BB_ASSIGNEE_ID])
GO
ALTER TABLE [dbo].[BB_APPLICATION_BASE] CHECK CONSTRAINT [FK_rvcmgrd38bs1va6exn18ea2j6]
GO
ALTER TABLE [dbo].[BB_VALID_FORMAT]  WITH CHECK ADD  CONSTRAINT [FK_7e37ouivf9uhbpsmmbfusgnhj] FOREIGN KEY([BB_VALIDATION_MATRIX_ID])
REFERENCES [dbo].[BB_VALIDATION_MATRIX] ([BB_VALIDATION_MATRIX_ID])
GO
ALTER TABLE [dbo].[BB_VALID_FORMAT] CHECK CONSTRAINT [FK_7e37ouivf9uhbpsmmbfusgnhj]
GO


USE [blackbox]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_ENTITY_USER](
	[BB_ENTITY_USER_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[ENTITY_NAME] [varchar](255) NOT NULL,
	[LOCK_ACQUIRED_ON] [datetime] NOT NULL,
	[LOCKED_BY] [numeric](19, 0) NOT NULL,
	[RECORD_ID] [numeric](19, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_ENTITY_USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO