USE [blackbox]
GO

/****** Object:  Table [dbo].[BB_QUEUE_VALIDATE_APPLICATION_PP]    Script Date: 12/2/2015 7:46:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BB_QUEUE_VALIDATE_APPLICATION_PP](
	[BB_QUEUE_VALIDATE_APPLICATION_PP_ID] [bigint] NOT NULL,
	[BB_CUSTOMER_NUMBER] [varchar](50) NOT NULL,
	[BB_APPLICATION_NUMBER] [varchar](50) NOT NULL,
	[BB_JURISDICTION_CODE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_BB_QUEUE_VALIDATE_APPLICATION_PP] PRIMARY KEY CLUSTERED 
(
	[BB_QUEUE_VALIDATE_APPLICATION_PP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [blackbox]
GO

/****** Object:  Table [dbo].[BB_WEB_CRAWLER_AUDIT]    Script Date: 12/23/2015 12:28:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_WEB_CRAWLER_AUDIT](
	[ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[ERROR_MESSAGE] [varchar](max) NULL,
	[JOB_STATUS] [varchar](255) NULL,
 CONSTRAINT [PK_BB_WEB_CRAWLER_AUDIT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [blackbox]
GO

/****** Object:  Table [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION]    Script Date: 12/23/2015 12:47:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION](
	[ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[APPLICATION_NUMBER_FORMATTED] [varchar](255) NOT NULL,
	[CUSTOMER_NUMBER] [varchar](255) NOT NULL,
	[JURISDICTION_CODE] [varchar](255) NOT NULL,
	[MAILING_DATE] [varchar](255) NULL,
	[DOCUMENT_CODE] [varchar](255) NULL,
	[RETRY_COUNT] [int] NULL,
	[STATUS] [varchar](50) NULL,
	[FILING_DATE] [datetime] NULL,
	[ATTACHMENT_PAGE_COUNT] [int] NULL,
	[CREATED_BY] [numeric](19, 0) NULL,
	[CREATED_ON] [datetime] NULL,
	[MODIFIED_BY] [numeric](19, 0) NULL,
	[MODIFIED_ON] [datetime] NULL,
	
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[BB_MSTR_AUTHENTICATION_DATA]    Script Date: 12/28/2015 10:06:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_MSTR_AUTHENTICATION_DATA](
	[BB_MSTR_AUTHENTICATION_DATA_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[PASSWORD] [varchar](255) NULL,
	[FILE_LOCATION_RELATIVE_PATH] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_MSTR_AUTHENTICATION_DATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


