update [BB_VALID_FORMAT] set [CONVERTER_STRATEGY] = 'REMOVE_CC' where  [BB_VALID_FORMAT_ID] = 9;
update [BB_VALID_FORMAT] set [CONVERTER_STRATEGY] = 'REMOVE_CC' where  [BB_VALID_FORMAT_ID] = 11;
update [BB_VALID_FORMAT] set [CONVERTER_STRATEGY] =' REMOVE_CC' where  [BB_VALID_FORMAT_ID] = 13;