-- Client
SET IDENTITY_INSERT [dbo].[BB_CLIENT] ON 
GO
INSERT [dbo].[BB_CLIENT] ([BB_CLIENT_ID], [MODIFIED_BY], [MODIFIED_ON], [CREATED_BY], [CREATED_ON], [VERSION], [CLIENT_TYPE], [EXPORT_FLAG], [NAME], [ORGANIZATION_TYPE], [VALIDATION_TYPE]) VALUES (CAST(-1 AS Numeric(19, 0)), CAST(-1 AS Numeric(19, 0)), CAST(N'2015-12-22 23:47:00.587' AS DateTime), CAST(1 AS Numeric(19, 0)), CAST(N'2015-12-22 23:47:00.587' AS DateTime), 1, N'LAW_FIRM', 1, N'Torry Morris', N'Law Firm', N'OCR_VALIDATION')
GO
SET IDENTITY_INSERT [dbo].[BB_CLIENT] OFF
GO

-- Technology Group
SET IDENTITY_INSERT [dbo].[BB_MSTR_TECHNOLOGY_GROUP] ON 
GO
INSERT [dbo].[BB_MSTR_TECHNOLOGY_GROUP] ([BB_TECHNOLOGY_GROUP_ID], [BB_CLIENT], [DESCRIPTION], [NAME]) VALUES (CAST(-1 AS Numeric(19, 0)), CAST(-1 AS Numeric(19, 0)), N'Technology Group I', N'TG1')
GO
SET IDENTITY_INSERT [dbo].[BB_MSTR_TECHNOLOGY_GROUP] OFF
GO
SET IDENTITY_INSERT [dbo].[BB_ORGANIZATION] ON 

-- Organization
GO
INSERT [dbo].[BB_ORGANIZATION] ([BB_ORGANIZATION_ID], [ADDRESS_1], [ADDRESS_2], [CITY], [BB_CLIENT], [COUNTRY], [NAME], [STATE], [ZIPCODE]) VALUES (CAST(-1 AS Numeric(19, 0)), NULL, NULL, NULL, CAST(-1 AS Numeric(19, 0)), N'US', N'Org Torry Morris', N'CA', N'10001')
GO
SET IDENTITY_INSERT [dbo].[BB_ORGANIZATION] OFF
GO

-- Customer
SET IDENTITY_INSERT [dbo].[BB_MSTR_CUSTOMER] ON 
GO
INSERT [dbo].[BB_MSTR_CUSTOMER] ([BB_CUSTOMER_ID], [CUSTOMER_NUMBER], [BB_MSTR_AUTHENTICATION_DATA]) VALUES (CAST(-1 AS Numeric(19, 0)), N'9999999999', NULL);
GO
SET IDENTITY_INSERT [dbo].[BB_MSTR_CUSTOMER] OFF
GO

-- Attorney Docket Format
GO
INSERT [dbo].[BB_MSTR_ATTORNEY_DOCKET_FORMAT] ([CLIENT_ID], [TOTAL_SEGMENTS], [SEGMENT_SIZE], [SEGMENT_TO_MATCH],[SEPARATOR]) VALUES (1, 4, 3, 2, '.');
GO

-- Assignee
SET IDENTITY_INSERT [dbo].[BB_ASSIGNEE] ON 
GO
INSERT [dbo].[BB_ASSIGNEE] ([BB_ASSIGNEE_ID], [BB_CLIENT], [DESCRIPTION], [ENTITY], [NAME]) VALUES (-1, 1, N'Default Assignee', N'SMALL', N'DEFAULT')
GO
INSERT [dbo].[BB_ASSIGNEE] ([BB_ASSIGNEE_ID], [BB_CLIENT], [DESCRIPTION], [ENTITY], [NAME]) VALUES (1, 1, N'Apple Inc.', N'UNDISCOUNTED', N'Apple')
GO
INSERT [dbo].[BB_ASSIGNEE] ([BB_ASSIGNEE_ID], [BB_CLIENT], [DESCRIPTION], [ENTITY], [NAME]) VALUES (2, 1, N'Samsung Inc.', N'UNDISCOUNTED', N'Samsung')
GO
SET IDENTITY_INSERT [dbo].[BB_ASSIGNEE] OFF
GO
