-- IDS Filing Fee
CREATE TABLE [dbo].[BB_MSTR_IDS_FILING_FEE](
	[BB_FILING_FEE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [bigint] NULL,
	[CREATED_ON] [datetime2](7) NULL,
	[MODIFIED_BY] [bigint] NULL,
	[MODIFIED_ON] [datetime2](7) NULL,
	[VERSION] [int] NULL,
	[END_DATE] [datetime2](7) NULL,
	[ENTITY] [varchar](255) NULL,
	[FEE] [float] NULL,
	[START_DATE] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_FILING_FEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
