USE [blackbox]
GO

INSERT INTO [dbo].[BB_MSTR_JURISDICTION]
           ([CODE]
           ,[DESCRIPTION])
     VALUES
           ('US'
           ,'UNITED STATES')
GO

INSERT INTO [dbo].[BB_MSTR_JURISDICTION]
           ([CODE]
           ,[DESCRIPTION])
     VALUES
           ('WO'
           ,'WO')
GO


USE [blackbox]
GO

INSERT INTO [dbo].[BB_INCLUSION_LIST]
           ([MODIFIED_BY]
           ,[MODIFIED_ON]
           ,[APPLICATION_NUMBER]
           ,[APPLICATION_NUMBER_RAW]
           ,[CHILD_APPLICATION_TYPE]
           ,[CUSTOMER_NUMBER]
           ,[FILING_DATE]
           ,[JURISDICTION]
           ,[STATUS])
     VALUES
           (1
           ,'2015-10-28 00:00:00.000'
           ,14933258
           ,14933258
           ,'FIRST_FILING'
           ,136388
           ,'2015-10-28 00:00:00.000'
           ,1
           ,'ACTIVE')
GO


USE [blackbox]
GO
SET IDENTITY_INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] ON 

INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] ([APPLICATION_NUMBER_FORMATTED], [CUSTOMER_NUMBER], [JURISDICTION_CODE], [DOCUMENT_CODE], [MAILING_DATE], [RETRY_COUNT], [STATUS], [FILING_DATE], [ATTACHMENT_PAGE_COUNT], [CREATED_BY], [CREATED_ON], [MODIFIED_BY], [MODIFIED_ON]) VALUES (N'14933258', N'136388', N'US', N'NTC.MISS.PRT', N'2015-11-20 00:00:00.000', 1, NULL, NULL, 2, NULL, NULL, NULL, NULL)
INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] ([APPLICATION_NUMBER_FORMATTED], [CUSTOMER_NUMBER], [JURISDICTION_CODE], [DOCUMENT_CODE], [MAILING_DATE], [RETRY_COUNT], [STATUS], [FILING_DATE], [ATTACHMENT_PAGE_COUNT], [CREATED_BY], [CREATED_ON], [MODIFIED_BY], [MODIFIED_ON]) VALUES (N'14933258', N'136388', N'US', N'APP.FILE.REC', N'2015-11-20 00:00:00.000', 1, NULL, NULL, 3, NULL, NULL, NULL, NULL)
INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] ([APPLICATION_NUMBER_FORMATTED], [CUSTOMER_NUMBER], [JURISDICTION_CODE], [DOCUMENT_CODE], [MAILING_DATE], [RETRY_COUNT], [STATUS], [FILING_DATE], [ATTACHMENT_PAGE_COUNT], [CREATED_BY], [CREATED_ON], [MODIFIED_BY], [MODIFIED_ON]) VALUES (N'14933258', N'136388', N'US', N'', N'', 1, NULL, NULL, 3, NULL, NULL, NULL, NULL)
INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] ([APPLICATION_NUMBER_FORMATTED], [CUSTOMER_NUMBER], [JURISDICTION_CODE], [DOCUMENT_CODE], [MAILING_DATE], [RETRY_COUNT], [STATUS], [FILING_DATE], [ATTACHMENT_PAGE_COUNT], [CREATED_BY], [CREATED_ON], [MODIFIED_BY], [MODIFIED_ON]) VALUES (N'17236623', N'136388', N'US', N'FOR', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] ([APPLICATION_NUMBER_FORMATTED], [CUSTOMER_NUMBER], [JURISDICTION_CODE], [DOCUMENT_CODE], [MAILING_DATE], [RETRY_COUNT], [STATUS], [FILING_DATE], [ATTACHMENT_PAGE_COUNT], [CREATED_BY], [CREATED_ON], [MODIFIED_BY], [MODIFIED_ON]) VALUES (N'9999', N'DummyCustomerNumber', N'US', N'FOR', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[BB_SCR_DOWNLOAD_OFFICE_ACTION] OFF


USE [blackbox]
GO

INSERT INTO [dbo].[BB_DOCUMENT_CODE]
           ([DOCUMENT_CODE]
           ,[DOCUMENT_DESCRIPTION])
     VALUES
           ('FR'
           ,'Foreign Reference')
GO


USE [blackbox]
GO

INSERT INTO [dbo].[BB_DOCUMENT_CODE]
           ([DOCUMENT_CODE]
           ,[DOCUMENT_DESCRIPTION])
     VALUES
           ('NTC.MISS.PRT',
           'Notice to File Missing Parts ')
GO

INSERT INTO [dbo].[BB_DOCUMENT_CODE]
           ([DOCUMENT_CODE]
           ,[DOCUMENT_DESCRIPTION])
     VALUES
           ('APP.FILE.REC',
           'Filing Receipt ')
GO

INSERT INTO [dbo].[BB_DOCUMENT_CODE]
           ([DOCUMENT_CODE]
           ,[DOCUMENT_DESCRIPTION])
     VALUES
           ('MES.GIB',
           'Test')
GO