USE @DATABASE_NAME@
GO

/****** Object:  Table [dbo].[BB_CORRESPONDENCE]    Script Date: 12/8/2015 4:45:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_CORRESPONDENCE](
	[BB_CORRESPONDENCE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BB_APPLICATION_ID] [bigint] NOT NULL,
	[MAILING_DATE] [datetime] NOT NULL,
	[BB_DOCUMENT_CODE_ID] [bigint] NOT NULL,
	[STATUS] [varchar](255) NOT NULL,
	[SOURCE] [varchar](255) NOT NULL,
	[SUB_SOURCE] [varchar](255) NOT NULL,
	[SPLIT_ID] [bigint] NULL,
	[PARENT_CHILD] [varchar](255) NULL,
	[COMMENT] [varchar](255) NULL,
	[ATTACHMENT_SIZE] [bigint] NOT NULL,
	[ATTACHMENT_PAGE_COUNT] [numeric](19, 0) NOT NULL,
	[STEP] [varchar](255) NOT NULL,
	[STEP_STATUS] [varchar](255) NOT NULL,
	[PRIVATE_PAIR_UPLOAD_DATE] [datetime]  NULL,
	[CREATED_ON] [datetime] NOT NULL,
	[CREATED_BY] [bigint] NOT NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_BY] [bigint] NULL,
	[VERSION] [int] NOT NULL,
 CONSTRAINT [PK_BB_CORRESPONDENCE] PRIMARY KEY CLUSTERED 
(
	[BB_CORRESPONDENCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_APPLICATION_BB_APPLICATION_ID_BB_CORRESPONDENCE] FOREIGN KEY([BB_APPLICATION_ID])
REFERENCES [dbo].[BB_APPLICATION] ([BB_APPLICATION_ID])
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE] NOCHECK CONSTRAINT [FK_BB_APPLICATION_BB_APPLICATION_ID_BB_CORRESPONDENCE]
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_DOCUMENT_CODE_BB_DOCUMENT_CODE_ID_BB_CORRESPONDENCE] FOREIGN KEY([BB_DOCUMENT_CODE_ID])
REFERENCES [dbo].[BB_DOCUMENT_CODE] ([BB_DOCUMENT_CODE_ID])
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE] NOCHECK CONSTRAINT [FK_BB_DOCUMENT_CODE_BB_DOCUMENT_CODE_ID_BB_CORRESPONDENCE]
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_CORRESPONDENCE_CREATED_BY] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[BB_USER] ([BB_USER_ID])
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE] NOCHECK CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_CORRESPONDENCE_CREATED_BY]
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_CORRESPONDENCE_MODIFIED_BY] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[BB_USER] ([BB_USER_ID])
GO

ALTER TABLE [dbo].[BB_CORRESPONDENCE] NOCHECK CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_CORRESPONDENCE_MODIFIED_BY]
GO



/******************-----------------------------------------------------------------------*************************/

/****** Object:  Table [dbo].[BB_CORRESPONDENCE_STAGING]    Script Date: 12/8/2015 5:43:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_CORRESPONDENCE_STAGING](
	[BB_CORRESPONDENCE_STAGING_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[APPLICATION_NUMBER] [varchar](255) NULL,
	[JURISDICTION_CODE] [varchar](255) NULL,
	[ATTACHMENT_NAME] [varchar] (255) NULL,
	[ATTACHMENT_SIZE] [bigint] NULL,
	[ATTACHMENT_PAGE_COUNT] [numeric](19, 0) NULL,
	[STATUS] [varchar](255) NULL,
	[COMMENT] [varchar](255) NULL,
	[CUSTOMER_NUMBER] [varchar](255) NULL,
	[DOCUMENT_CODE] [varchar](255) NULL,
	[DOCUMENT_DESCRIPTION] [varchar](255) NULL,
	[N417_EFS_ID] [varchar](255) NULL,
	[PRIVATE_PAIR_UPLOAD_DATE] [datetime] NULL,
	[MAILING_DATE] [datetime] NULL,
	[FILING_DATE] [datetime] NULL,
	[PARENT_CHILD] [varchar](255) NULL,
	[SOURCE] [varchar](255) NULL,
	[SUB_SOURCE] [varchar](255) NULL,
	[SPLIT_ID] [bigint] NULL,
	[ASSIGNEE] [varchar](255) NULL,
	[CREATED_BY] [numeric](19, 0) NOT NULL,
	[CREATED_ON] [datetime] NOT NULL,
	[MODIFIED_BY] [numeric](19, 0) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[VERSION] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_CORRESPONDENCE_STAGING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


/****** Object:  Table [dbo].[BB_PAIR_AUDIT]    Script Date: 11-12-2015 11:01:31 ******/
DROP TABLE [dbo].[BB_PAIR_AUDIT]
GO

/****** Object:  Table [dbo].[BB_PAIR_AUDIT]    Script Date: 11-12-2015 11:01:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_PAIR_AUDIT](
	[BB_PAIR_AUDIT_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[AUDIT_DATE] [datetime] NOT NULL,
	[PERFORMED_BY] [varchar](255) NOT NULL,
	[JURISDICTION] [varchar](255) NOT NULL,
	[APPLICATION_NUMBER] [varchar](255) NOT NULL,
	[MAILING_DATE] [datetime] NOT NULL,
	[DOCUMENT_CODE] [varchar](255) NULL,
	[NUMBER_OF_PAGES] [numeric](19, 0) NOT NULL,
	[STATUS_OF_RECORD] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_PAIR_AUDIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER table [dbo].[BB_CORRESPONDENCE]
add N417_EFS_ID nvarchar(50);

GO

