USE @DATABASE_NAME@

/****** Object:  Table [dbo].[BB_MESSAGE]    Script Date: 12/1/2015 6:19:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_MESSAGE](
	[BB_MESSAGE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TEMPLATE_TYPE] [varchar](255) NOT NULL,
	[RECEIVER_LIST] [varchar](255) NOT NULL,
	[STATUS] [varchar](255) NOT NULL,
	[CREATED_ON] [datetime] NOT NULL,
	[CREATED_BY] [bigint] NOT NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_BY] [bigint] NULL,
	[VERSION] [int] NOT NULL,
 CONSTRAINT [PK_BB_MESSAGE] PRIMARY KEY CLUSTERED 
(
	[BB_MESSAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BB_MESSAGE]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_MESSAGE_CREATED_BY] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[BB_USER] ([BB_USER_ID])
GO

ALTER TABLE [dbo].[BB_MESSAGE] NOCHECK CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_MESSAGE_CREATED_BY]
GO

ALTER TABLE [dbo].[BB_MESSAGE]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_MESSAGE_MODIFIED_BY] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[BB_USER] ([BB_USER_ID])
GO

ALTER TABLE [dbo].[BB_MESSAGE] NOCHECK CONSTRAINT [FK_BB_USER_BB_USER_ID_BB_MESSAGE_MODIFIED_BY]
GO

/**********************************************************************************************************************/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BB_MESSAGE_DATA](
	[BB_MESSAGE_DATA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[KEY] [varchar](50) NOT NULL,
	[VALUE] [varchar](100) NOT NULL,
	[BB_MESSAGE_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_BB_MESSAGE_DATA] PRIMARY KEY CLUSTERED 
(
	[BB_MESSAGE_DATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BB_MESSAGE_DATA]  WITH NOCHECK ADD  CONSTRAINT [FK_BB_MESSAGE_BB_MESSAGE_ID_BB_MESSAGE_DATA] FOREIGN KEY([BB_MESSAGE_ID])
REFERENCES [dbo].[BB_MESSAGE] ([BB_MESSAGE_ID])
GO

ALTER TABLE [dbo].[BB_MESSAGE_DATA] NOCHECK CONSTRAINT [FK_BB_MESSAGE_BB_MESSAGE_ID_BB_MESSAGE_DATA]

