USE [blackbox]
GO
/****** Object:  Table [dbo].[BB_NOTIFICATION]    Script Date: 27-Nov-2015 12:28:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_NOTIFICATION](
	[BB_NOTIFICATION_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[NOTIFICATION_LEVEL] [int] NOT NULL,
	[PROCESS_NAME] [varchar](50) NULL,
	[CODE] [varchar](50) NULL,
	[SUBJECT] [varchar](50) NULL,
	[MESSAGE] [varchar](500) NULL,
	[REMINDER] [bit] NULL,
	[IDS_REVIEW_DISPLAY] [bit] NOT NULL,
	[EMAIL_NOTIFICATION] [bit] NOT NULL,
	[NO_OF_REMINDERS] [int] NOT NULL,
	[FREQUENCY_OF_SENDING_REMINDERS] [int] NOT NULL,
	[ESCALATION] [bit] NOT NULL,
	[NO_OF_PAST_DUE_DAYS] [int] NULL,
	[PARENT] [bigint] NULL,
	[IS_ACTIVE] [bit] NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_BY] [bigint] NULL,
	[MODIFIED_BY] [numeric](19, 0) NULL,
	[MODIFIED_ON] [datetime] NULL,
	[VERSION] [int] NULL,
 CONSTRAINT [PK_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[BB_NOTIFICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BB_NOTIFICATION_BUSINESS_RULE]    Script Date: 27-Nov-2015 12:28:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BB_NOTIFICATION_BUSINESS_RULE](
	[BB_NOTIFICATION_BUSINESS_RULE_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[BB_NOTIFICATION_ID] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_NOTIFICATION_BUSINESS_RULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BB_NOTIFICATION_BUSINESS_RULE_LEVEL]    Script Date: 27-Nov-2015 12:28:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BB_NOTIFICATION_BUSINESS_RULE_LEVEL](
	[BB_NOTIFICATION_BUSINESS_RULE_LEVEL_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[LEVEL_NUMBER] [int] NULL,
	[BB_NOTIFICATION_BUSINESS_RULE_ID] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_NOTIFICATION_BUSINESS_RULE_LEVEL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BB_NOTIFICATION_DEFAULT_ROLE]    Script Date: 27-Nov-2015 12:28:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BB_NOTIFICATION_DEFAULT_ROLE](
	[BB_NOTIFICATION_DEFAULT_ROLE_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[BB_NOTIFICATION_ID] [numeric](19, 0) NULL,
	[BB_ROLE_ID] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_NOTIFICATION_DEFAULT_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BB_NOTIFICATION_ESCALATION_ROLE]    Script Date: 27-Nov-2015 12:28:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BB_NOTIFICATION_ESCALATION_ROLE](
	[BB_NOTIFICATION_ESCALATION_ROLE_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[BB_NOTIFICATION_ID] [numeric](19, 0) NULL,
	[BB_ROLE_ID] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_NOTIFICATION_ESCALATION_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BB_NOTIFICATION_LEVEL_ROLE]    Script Date: 27-Nov-2015 12:28:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BB_NOTIFICATION_LEVEL_ROLE](
	[BB_NOTIFICATION_LEVEL_ROLE_ID] [numeric](19, 0) IDENTITY(1,1) NOT NULL,
	[BB_NOTIFICATION_BUSINESS_RULE_LEVEL_ID] [numeric](19, 0) NULL,
	[TYPE] [varchar](255) NULL,
	[BB_ROLE_ID] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[BB_NOTIFICATION_LEVEL_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[BB_NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_8jtw2e3us9uhy0wbgj9x5wdcf] FOREIGN KEY([PARENT])
REFERENCES [dbo].[BB_NOTIFICATION] ([BB_NOTIFICATION_ID])
GO
ALTER TABLE [dbo].[BB_NOTIFICATION] CHECK CONSTRAINT [FK_8jtw2e3us9uhy0wbgj9x5wdcf]
GO
ALTER TABLE [dbo].[BB_NOTIFICATION_BUSINESS_RULE_LEVEL]  WITH CHECK ADD  CONSTRAINT [FK_m1ibw2x9xnd6ruciyvmepoe79] FOREIGN KEY([BB_NOTIFICATION_BUSINESS_RULE_ID])
REFERENCES [dbo].[BB_NOTIFICATION_BUSINESS_RULE] ([BB_NOTIFICATION_BUSINESS_RULE_ID])
GO
ALTER TABLE [dbo].[BB_NOTIFICATION_BUSINESS_RULE_LEVEL] CHECK CONSTRAINT [FK_m1ibw2x9xnd6ruciyvmepoe79]
GO
ALTER TABLE [dbo].[BB_NOTIFICATION_LEVEL_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_io31w4nv7m37fv6ooewwisdjc] FOREIGN KEY([BB_NOTIFICATION_BUSINESS_RULE_LEVEL_ID])
REFERENCES [dbo].[BB_NOTIFICATION_BUSINESS_RULE_LEVEL] ([BB_NOTIFICATION_BUSINESS_RULE_LEVEL_ID])
GO
ALTER TABLE [dbo].[BB_NOTIFICATION_LEVEL_ROLE] CHECK CONSTRAINT [FK_io31w4nv7m37fv6ooewwisdjc]
GO
