 USE [blackbox]

 ALTER TABLE [BB_APPLICATION_BASE] ADD [BB_COMMENT] [varchar](255) NULL;
 
 ALTER TABLE [BB_APPLICATION_BASE] ADD [BB_NEW_RECORD_STATUS] [varchar](255) DEFAULT NULL;
 
 ALTER TABLE [BB_APPLICATION_BASE] ADD [PARENT_RECORD] BIT NOT NULL DEFAULT 1;
 
 -- Application Stage :: Unique constraint
ALTER TABLE dbo.BB_APPLICATION_STAGE ADD CONSTRAINT UN_APP_JUR_SOURCE UNIQUE (APPLICATION_NUMBER, BB_JURISDICTION, SOURCE, CREATED_BY);